### ISSUE TITLE
Adapter拼写问题

### ISSUE THREAD

**Issue by shipengtaov** [xuwu125/HuicuiApi#2]
HuicuiApi/src/HuicuiApi/Exception/HuicuiApiApapterException.php 这个文件是不是 HuicuiApiAdapterException.php，Adapter写成了Apapter

**Comment by xuwu125** [comment]
收到，这里确实拼写错误，已经修复

**Comment by shipengtaov** [comment]
请问有Python SDK吗

**Comment by xuwu125** [comment]
目前还没有，准备近期推出。

2017-05-08 15:41 GMT+08:00 PengTao.Shi <notifications@github.com>:
